#!/usr/bin/env python3
"""
Generates database/seed-master-data-dump.sql — a large, realistic data set
covering every table in the Quiz Admin Portal schema, sized for genuine
performance testing (hundreds of rows per table, not a handful of demo rows).

All explicit primary keys start at 1000+ per table so they can NEVER collide
with the small set of rows DataSeeder.java creates on first boot (roles 1-4,
users 1-4, question_types 1-5, difficulty_levels 1-3). That means this dump
is safe to run either before or after the app's first startup.

Run:  python3 generate_seed_dump.py
Output: seed-master-data-dump.sql (in the same directory)
"""
import random

random.seed(42)  # reproducible output on every run

OUT = []
def sql(line):
    OUT.append(line)

def esc(s):
    return s.replace("'", "''")

BCRYPT_HASH = "$2b$10$i83xrBROjQgCgt4qzBzDB.8cCo/qoI/lspFM/G9d/kvPEhvJg334S"  # bcrypt("Password@123")

# ----------------------------------------------------------------------
# Header
# ----------------------------------------------------------------------
sql("-- ============================================================")
sql("-- Quiz Admin Portal — Master Data Dump (performance test dataset)")
sql("-- Generated by database/generate_seed_dump.py")
sql("--")
sql("-- Every seeded user's password is: Password@123")
sql("-- (bcrypt hash below, verifiable by Spring Security's BCryptPasswordEncoder)")
sql("--")
sql("-- Safe to run on a fresh DB or one already started by the app once —")
sql("-- all explicit IDs here start at 1000+, well clear of the handful of")
sql("-- rows DataSeeder.java creates (ids 1-5 across a few tables).")
sql("-- ============================================================")
sql("")
sql("SET FOREIGN_KEY_CHECKS=0;")
sql("SET NAMES utf8mb4;")
sql("")

# ----------------------------------------------------------------------
# Roles (idempotent — matches DataSeeder's own 4 roles by unique name)
# ----------------------------------------------------------------------
sql("-- ---------------- Roles ----------------")
roles = [
    (1000, "ROLE_ADMIN", "Full system access"),
    (1001, "ROLE_REVIEWER", "Reviews and approves questions"),
    (1002, "ROLE_INSTRUCTOR", "Creates quizzes and questions"),
    (1003, "ROLE_STUDENT", "Takes quizzes"),
]
for rid, name, desc in roles:
    sql(f"INSERT INTO roles (id, name, description) VALUES ({rid}, '{name}', '{esc(desc)}') "
        f"ON DUPLICATE KEY UPDATE description=VALUES(description);")
sql("")

# lookup helpers: role name -> id actually used (post ON DUPLICATE, IDs may
# differ if DataSeeder ran first — so downstream inserts resolve by name)
ROLE_ADMIN, ROLE_REVIEWER, ROLE_INSTRUCTOR, ROLE_STUDENT = 1000, 1001, 1002, 1003

# ----------------------------------------------------------------------
# Users
# ----------------------------------------------------------------------
sql("-- ---------------- Users ----------------")
FIRST_NAMES = ["Aarav","Vivaan","Aditya","Vihaan","Arjun","Sai","Reyansh","Krishna","Ishaan","Rohan",
               "Ananya","Diya","Isha","Kavya","Myra","Aadhya","Anika","Navya","Riya","Saanvi",
               "James","Olivia","Liam","Emma","Noah","Ava","Ethan","Sophia","Mason","Isabella",
               "Lucas","Mia","Henry","Amelia","Alex","Grace","Daniel","Chloe","Ryan","Zoe"]
LAST_NAMES = ["Sharma","Verma","Patel","Gupta","Reddy","Nair","Iyer","Kapoor","Malhotra","Chopra",
              "Smith","Johnson","Williams","Brown","Jones","Miller","Davis","Garcia","Clark","Lewis"]

def full_name(i):
    return f"{FIRST_NAMES[i % len(FIRST_NAMES)]} {LAST_NAMES[(i * 7) % len(LAST_NAMES)]}"

users = []  # (id, fullName, email, phone, roleId)
uid = 2000

# 5 admins
for i in range(5):
    users.append((uid, full_name(uid), f"admin{i+1}@quizapp.com", f"98{1000000+uid}", ROLE_ADMIN)); uid += 1
# 12 instructors
for i in range(12):
    users.append((uid, full_name(uid), f"instructor{i+1}@quizapp.com", f"97{1000000+uid}", ROLE_INSTRUCTOR)); uid += 1
# 8 reviewers
for i in range(8):
    users.append((uid, full_name(uid), f"reviewer{i+1}@quizapp.com", f"96{1000000+uid}", ROLE_REVIEWER)); uid += 1
# 55 students
for i in range(55):
    users.append((uid, full_name(uid), f"student{i+1}@quizapp.com", f"95{1000000+uid}", ROLE_STUDENT)); uid += 1

for user_id, name, email, phone, _role in users:
    sql(f"INSERT INTO users (id, full_name, email, phone, password, enabled, email_verified, created_at, updated_at) "
        f"VALUES ({user_id}, '{esc(name)}', '{email}', '{phone}', '{BCRYPT_HASH}', 1, 1, NOW(), NOW()) "
        f"ON DUPLICATE KEY UPDATE full_name=VALUES(full_name);")
sql("")

sql("-- user_roles (many-to-many)")
for user_id, _name, _email, _phone, role_id in users:
    sql(f"INSERT IGNORE INTO user_roles (user_id, role_id) VALUES ({user_id}, {role_id});")
sql("")

student_ids = [u[0] for u in users if u[4] == ROLE_STUDENT]
instructor_ids = [u[0] for u in users if u[4] == ROLE_INSTRUCTOR]
reviewer_ids = [u[0] for u in users if u[4] == ROLE_REVIEWER]

# ----------------------------------------------------------------------
# User Groups
# ----------------------------------------------------------------------
sql("-- ---------------- User Groups ----------------")
groups = [
    (3000, "Batch 2025 - Morning", "Morning batch students, 2025 intake"),
    (3001, "Batch 2025 - Evening", "Evening batch students, 2025 intake"),
    (3002, "Advanced Learners", "Students in advanced-track courses"),
    (3003, "Certification Track", "Students pursuing certification exams"),
    (3004, "Remedial Group", "Students in the remedial support program"),
    (3005, "Placement Prep", "Students preparing for placement drives"),
]
for gid, name, desc in groups:
    sql(f"INSERT INTO user_groups (id, name, description) VALUES ({gid}, '{esc(name)}', '{esc(desc)}') "
        f"ON DUPLICATE KEY UPDATE description=VALUES(description);")
sql("")

sql("-- user_group_members (many-to-many) — scatter students across groups")
for s in student_ids:
    for g in random.sample([g[0] for g in groups], k=random.randint(1, 2)):
        sql(f"INSERT IGNORE INTO user_group_members (user_id, group_id) VALUES ({s}, {g});")
sql("")

# ----------------------------------------------------------------------
# Master Data: Subjects, Categories, Difficulty Levels, Question Types, Tags
# ----------------------------------------------------------------------
sql("-- ---------------- Subjects ----------------")
subjects = [
    (4000, "Mathematics"), (4001, "Science"), (4002, "English Language"),
    (4003, "History"), (4004, "Geography"), (4005, "Computer Science"),
    (4006, "Physics"), (4007, "Chemistry"), (4008, "Biology"),
    (4009, "General Knowledge"),
]
for sid, name in subjects:
    sql(f"INSERT INTO subjects (id, name, description, active) VALUES "
        f"({sid}, '{esc(name)}', '{esc(name)} — core curriculum subject', 1);")
sql("")

sql("-- ---------------- Categories (3 per subject) ----------------")
CATEGORY_SUFFIXES = ["Fundamentals", "Advanced Topics", "Applied Concepts"]
categories = []
cid = 5000
for sid, sname in subjects:
    for suffix in CATEGORY_SUFFIXES:
        categories.append((cid, f"{sname} - {suffix}", sid))
        cid += 1
for cid, name, sid in categories:
    sql(f"INSERT INTO categories (id, name, subject_id, active) VALUES ({cid}, '{esc(name)}', {sid}, 1);")
sql("")

sql("-- ---------------- Difficulty Levels ----------------")
difficulty_levels = [(6000, "Easy", 1), (6001, "Medium", 2), (6002, "Hard", 3)]
for did, name, weight in difficulty_levels:
    sql(f"INSERT INTO difficulty_levels (id, name, weight) VALUES ({did}, '{name}', {weight}) "
        f"ON DUPLICATE KEY UPDATE weight=VALUES(weight);")
sql("")

sql("-- ---------------- Question Types ----------------")
question_types = [(7000, "SINGLE_CHOICE"), (7001, "MULTIPLE_CHOICE"), (7002, "TRUE_FALSE"),
                   (7003, "FILL_IN_THE_BLANK"), (7004, "DESCRIPTIVE")]
for tid, name in question_types:
    sql(f"INSERT INTO question_types (id, name) VALUES ({tid}, '{name}') "
        f"ON DUPLICATE KEY UPDATE name=VALUES(name);")
sql("")

sql("-- ---------------- Tags ----------------")
tag_names = ["exam-prep","conceptual","numerical","previous-year","tricky","beginner-friendly",
             "high-weightage","formula-based","diagram-based","memory-based","logical-reasoning",
             "quick-revision","must-practice","common-mistake","time-consuming","short-answer",
             "objective","application-based","theory","case-study"]
tags = [(8000 + i, name) for i, name in enumerate(tag_names)]
for tid, name in tags:
    sql(f"INSERT INTO tags (id, name) VALUES ({tid}, '{name}') ON DUPLICATE KEY UPDATE name=VALUES(name);")
sql("")

# ----------------------------------------------------------------------
# Questions + Options + Tags (the big performance-relevant table)
# ----------------------------------------------------------------------
sql("-- ---------------- Questions (400 rows — the main pagination/perf test table) ----------------")

QUESTION_STEMS = [
    "What is the correct definition of {topic}?",
    "Which of the following best describes {topic}?",
    "Identify the key characteristic of {topic}.",
    "Solve the problem related to {topic} below.",
    "Which statement about {topic} is TRUE?",
    "Which statement about {topic} is FALSE?",
    "What is the primary use case for {topic}?",
    "Calculate the result involving {topic}.",
    "Which of these is an example of {topic}?",
    "What year / value is most closely associated with {topic}?",
]
TOPICS_BY_SUBJECT = {
    "Mathematics": ["algebra", "geometry", "probability", "calculus", "trigonometry", "statistics"],
    "Science": ["photosynthesis", "Newton's laws", "the periodic table", "cell structure", "energy conservation"],
    "English Language": ["subject-verb agreement", "figures of speech", "tenses", "comprehension", "vocabulary"],
    "History": ["the industrial revolution", "world war II", "ancient civilizations", "colonialism", "the renaissance"],
    "Geography": ["plate tectonics", "climate zones", "river systems", "population distribution", "urbanization"],
    "Computer Science": ["data structures", "algorithms", "databases", "operating systems", "networking"],
    "Physics": ["Newton's laws of motion", "thermodynamics", "optics", "electromagnetism", "quantum mechanics"],
    "Chemistry": ["chemical bonding", "acids and bases", "the periodic table", "organic reactions", "stoichiometry"],
    "Biology": ["cell division", "genetics", "the human circulatory system", "ecosystems", "evolution"],
    "General Knowledge": ["world capitals", "current affairs", "famous inventions", "sports records", "awards and honors"],
}

status_pool = (["APPROVED"] * 70) + (["PENDING_REVIEW"] * 20) + (["REJECTED"] * 7) + (["DRAFT"] * 3)

questions = []  # (id, subject_id, category_id, difficulty_id, qtype_id, status, created_by)
qid = 9000
for sid, sname in subjects:
    subj_categories = [c for c in categories if c[2] == sid]
    topics = TOPICS_BY_SUBJECT[sname]
    for _ in range(40):  # 40 questions per subject x 10 subjects = 400
        topic = random.choice(topics)
        stem = random.choice(QUESTION_STEMS).format(topic=topic)
        cat = random.choice(subj_categories)
        diff = random.choice(difficulty_levels)
        qtype = random.choice(question_types[:3])  # keep to choice-style types so options make sense
        status = random.choice(status_pool)
        created_by = random.choice(instructor_ids)
        reviewed_by = random.choice(reviewer_ids) if status in ("APPROVED", "REJECTED") else None
        marks = random.choice([1, 1, 1, 2, 2, 5])
        negative_marks = random.choice([0, 0, 0, 1])

        questions.append((qid, sid, cat[0], diff[0], qtype[0], status, created_by, reviewed_by, marks, negative_marks))

        review_comment = "'Looks good, approved.'" if status == "APPROVED" else \
                          ("'Needs clearer wording, rejected.'" if status == "REJECTED" else "NULL")
        reviewed_by_sql = str(reviewed_by) if reviewed_by else "NULL"

        sql(f"INSERT INTO questions (id, question_text, subject_id, category_id, difficulty_id, question_type_id, "
            f"marks, negative_marks, status, explanation, created_by, reviewed_by, review_comments, created_at, updated_at) "
            f"VALUES ({qid}, '{esc(stem)}', {sid}, {cat[0]}, {diff[0]}, {qtype[0]}, {marks}, {negative_marks}, "
            f"'{status}', 'Refer to the {esc(topic)} chapter for a full explanation.', {created_by}, {reviewed_by_sql}, "
            f"{review_comment}, NOW(), NOW());")
        qid += 1
sql("")

sql("-- ---------------- Question Options (4 per choice-question, 2 for TRUE_FALSE) ----------------")
opt_id = 10000
OPTION_LABELS = ["Option A text", "Option B text", "Option C text", "Option D text"]
TRUE_FALSE_TYPE_ID = question_types[2][0]  # 7002
for q in questions:
    q_id, _sid, _cid, _did, qtype_id = q[0], q[1], q[2], q[3], q[4]
    if qtype_id == TRUE_FALSE_TYPE_ID:
        correct_index = random.randint(0, 1)
        for i, label in enumerate(["True", "False"]):
            is_correct = 1 if i == correct_index else 0
            sql(f"INSERT INTO question_options (id, question_id, option_text, is_correct, option_order) "
                f"VALUES ({opt_id}, {q_id}, '{label}', {is_correct}, {i+1});")
            opt_id += 1
    else:
        correct_index = random.randint(0, 3)
        for i in range(4):
            is_correct = 1 if i == correct_index else 0
            text = f"{OPTION_LABELS[i]} for question {q_id}"
            sql(f"INSERT INTO question_options (id, question_id, option_text, is_correct, option_order) "
                f"VALUES ({opt_id}, {q_id}, '{esc(text)}', {is_correct}, {i+1});")
            opt_id += 1
sql("")

sql("-- ---------------- Question Tags (1-3 tags per question) ----------------")
for q in questions:
    q_id = q[0]
    for t in random.sample(tags, k=random.randint(1, 3)):
        sql(f"INSERT IGNORE INTO question_tags (question_id, tag_id) VALUES ({q_id}, {t[0]});")
sql("")

approved_questions = [q for q in questions if q[5] == "APPROVED"]

# ----------------------------------------------------------------------
# Quizzes + Quiz Questions + Quiz Schedules + Quiz Assignments
# ----------------------------------------------------------------------
sql("-- ---------------- Quizzes (30 rows) ----------------")
QUIZ_NAME_TEMPLATES = ["{subj} Mock Test {n}", "{subj} Weekly Quiz {n}", "{subj} Chapter Test {n}", "{subj} Final Assessment {n}"]
quizzes = []  # (id, subject_id, duration, total_marks, passing_marks, created_by)
quiz_id = 20000
for i in range(30):
    sid, sname = random.choice(subjects)
    title = random.choice(QUIZ_NAME_TEMPLATES).format(subj=sname, n=(i % 5) + 1)
    duration = random.choice([15, 20, 30, 45, 60])
    created_by = random.choice(instructor_ids)
    active = 1 if random.random() > 0.15 else 0

    subj_questions = [q for q in approved_questions if q[1] == sid]
    chosen = random.sample(subj_questions, k=min(10, len(subj_questions))) if subj_questions else []
    total_marks = sum(q[8] for q in chosen) if chosen else 10
    passing_marks = max(1, int(total_marks * 0.4))

    quizzes.append((quiz_id, sid, duration, total_marks, passing_marks, created_by, chosen))

    sql(f"INSERT INTO quizzes (id, title, description, subject_id, duration_minutes, total_marks, passing_marks, "
        f"shuffle_questions, active, created_by, created_at) VALUES "
        f"({quiz_id}, '{esc(title)}', 'Auto-generated quiz covering {esc(sname)} topics.', {sid}, {duration}, "
        f"{total_marks}, {passing_marks}, 1, {active}, {created_by}, NOW());")
    quiz_id += 1
sql("")

sql("-- ---------------- Quiz Questions (linking table) ----------------")
qq_id = 21000
for q_row in quizzes:
    quiz_id_ref, _sid, _dur, _tm, _pm, _cb, chosen = q_row
    for order, question in enumerate(chosen, start=1):
        sql(f"INSERT INTO quiz_questions (id, quiz_id, question_id, question_order) "
            f"VALUES ({qq_id}, {quiz_id_ref}, {question[0]}, {order});")
        qq_id += 1
sql("")

sql("-- ---------------- Quiz Schedules (mix of past/current/future, to test OPEN/UPCOMING/EXPIRED) ----------------")
sched_id = 22000
for q_row in quizzes:
    quiz_id_ref = q_row[0]
    bucket = random.choice(["past", "current", "future", "current", "future"])  # weight toward testable states
    if bucket == "past":
        start_offset, end_offset = -14, -7   # closed 7+ days ago
    elif bucket == "current":
        start_offset, end_offset = -2, 5     # open right now
    else:
        start_offset, end_offset = 3, 10     # opens in the future

    sql(f"INSERT INTO quiz_schedules (id, quiz_id, start_time, end_time, active) VALUES "
        f"({sched_id}, {quiz_id_ref}, DATE_ADD(NOW(), INTERVAL {start_offset} DAY), "
        f"DATE_ADD(NOW(), INTERVAL {end_offset} DAY), 1);")
    sched_id += 1
sql("")

sql("-- ---------------- Quiz Assignments (direct-to-user and to-group, mixed) ----------------")
assign_id = 23000
for q_row in quizzes:
    quiz_id_ref = q_row[0]
    # assign to 3-6 random students directly
    for s in random.sample(student_ids, k=random.randint(3, 6)):
        sql(f"INSERT INTO quiz_assignments (id, quiz_id, user_id, group_id) VALUES ({assign_id}, {quiz_id_ref}, {s}, NULL);")
        assign_id += 1
    # and to 1-2 random groups
    for g in random.sample([g[0] for g in groups], k=random.randint(1, 2)):
        sql(f"INSERT INTO quiz_assignments (id, quiz_id, user_id, group_id) VALUES ({assign_id}, {quiz_id_ref}, NULL, {g});")
        assign_id += 1
sql("")

# ----------------------------------------------------------------------
# Quiz Results (completed attempts + a handful of in-progress ones)
# ----------------------------------------------------------------------
sql("-- ---------------- Quiz Results (300 completed + 15 in-progress, for Live Monitoring) ----------------")
result_id = 24000
for _ in range(300):
    q_row = random.choice(quizzes)
    quiz_id_ref, _sid, _dur, total_marks, passing_marks, _cb, _chosen = q_row
    student = random.choice(student_ids)
    score = round(random.uniform(0, total_marks), 1) if total_marks > 0 else 0
    passed = 1 if score >= passing_marks else 0
    days_ago = random.randint(0, 60)
    sql(f"INSERT INTO quiz_results (id, quiz_id, user_id, score_obtained, total_marks, passed, started_at, submitted_at) "
        f"VALUES ({result_id}, {quiz_id_ref}, {student}, {score}, {total_marks}, {passed}, "
        f"DATE_SUB(NOW(), INTERVAL {days_ago} DAY), DATE_SUB(NOW(), INTERVAL {days_ago} DAY));")
    result_id += 1

# in-progress attempts (submitted_at NULL) — exercises the Live Monitoring page
for _ in range(15):
    q_row = random.choice(quizzes)
    quiz_id_ref, _sid, _dur, total_marks, _pm, _cb, _chosen = q_row
    student = random.choice(student_ids)
    minutes_ago = random.randint(1, 20)
    sql(f"INSERT INTO quiz_results (id, quiz_id, user_id, score_obtained, total_marks, passed, started_at, submitted_at) "
        f"VALUES ({result_id}, {quiz_id_ref}, {student}, 0, {total_marks}, 0, "
        f"DATE_SUB(NOW(), INTERVAL {minutes_ago} MINUTE), NULL);")
    result_id += 1
sql("")

# ----------------------------------------------------------------------
# Invitations
# ----------------------------------------------------------------------
sql("-- ---------------- Invitations ----------------")
inv_id = 25000
inv_status_pool = (["PENDING"] * 6) + (["ACCEPTED"] * 3) + (["EXPIRED"] * 1)
for _ in range(50):
    q_row = random.choice(quizzes)
    quiz_id_ref = q_row[0]
    email = f"invitee{inv_id}@example.com"
    status = random.choice(inv_status_pool)
    days_ago = random.randint(0, 30)
    sql(f"INSERT INTO invitations (id, quiz_id, email, status, sent_at) VALUES "
        f"({inv_id}, {quiz_id_ref}, '{email}', '{status}', DATE_SUB(NOW(), INTERVAL {days_ago} DAY));")
    inv_id += 1
sql("")

# ----------------------------------------------------------------------
# Practice Sets + Practice Attempts
# ----------------------------------------------------------------------
sql("-- ---------------- Practice Sets ----------------")
practice_sets = []
ps_id = 26000
for sid, sname in subjects[:8]:
    title = f"{sname} Self-Practice Pack"
    practice_sets.append((ps_id, sid))
    sql(f"INSERT INTO practice_sets (id, title, subject_id, description, active, created_at) VALUES "
        f"({ps_id}, '{esc(title)}', {sid}, 'Untimed self-practice covering {esc(sname)}.', 1, NOW());")
    ps_id += 1
sql("")

sql("-- ---------------- Practice Attempts (200 rows) ----------------")
pa_id = 27000
for _ in range(200):
    ps = random.choice(practice_sets)
    student = random.choice(student_ids)
    score_pct = round(random.uniform(20, 100), 1)
    days_ago = random.randint(0, 45)
    sql(f"INSERT INTO practice_attempts (id, practice_set_id, user_id, score_obtained, attempted_at) VALUES "
        f"({pa_id}, {ps[0]}, {student}, {score_pct}, DATE_SUB(NOW(), INTERVAL {days_ago} DAY));")
    pa_id += 1
sql("")

# ----------------------------------------------------------------------
# Notifications + Announcements
# ----------------------------------------------------------------------
sql("-- ---------------- SMS / Email / Push Notifications ----------------")
sms_id = 28000
for i in range(25):
    student = random.choice(student_ids)
    phone = f"9500{sms_id}"
    sql(f"INSERT INTO sms_notifications (id, recipient_phone, message, status, sent_at) VALUES "
        f"({sms_id}, '{phone}', 'Reminder: your quiz starts soon. Good luck!', 'SENT', "
        f"DATE_SUB(NOW(), INTERVAL {random.randint(0,20)} DAY));")
    sms_id += 1
sql("")

email_id = 28100
for i in range(25):
    student = random.choice(student_ids)
    sql(f"INSERT INTO email_notifications (id, recipient_email, subject, body, status, sent_at) VALUES "
        f"({email_id}, 'student{i+1}@quizapp.com', 'Your quiz results are ready', "
        f"'Log in to the portal to view your latest quiz results.', 'SENT', "
        f"DATE_SUB(NOW(), INTERVAL {random.randint(0,20)} DAY));")
    email_id += 1
sql("")

push_id = 28200
for i in range(25):
    sql(f"INSERT INTO push_notifications (id, title, body, status, sent_at) VALUES "
        f"({push_id}, 'New quiz available', 'A new quiz has been assigned to you.', 'SENT', "
        f"DATE_SUB(NOW(), INTERVAL {random.randint(0,20)} DAY));")
    push_id += 1
sql("")

sql("-- ---------------- Announcements ----------------")
ann_id = 28300
announcements = [
    "Platform maintenance scheduled this weekend.",
    "New certification track now available!",
    "Deadline extended for the placement prep batch.",
    "Congratulations to our top scorers this month.",
    "New question bank content added for Computer Science.",
    "Reminder: complete your pending quizzes before the term ends.",
    "Instructor office hours updated — check your schedule.",
    "Mobile-friendly redesign is now live across the portal.",
    "Practice sets refreshed with new questions.",
    "Welcome to the new academic term!",
]
for i, msg in enumerate(announcements):
    sql(f"INSERT INTO announcements (id, title, message, active, created_at) VALUES "
        f"({ann_id}, 'Announcement #{i+1}', '{esc(msg)}', 1, DATE_SUB(NOW(), INTERVAL {i*2} DAY));")
    ann_id += 1
sql("")

# ----------------------------------------------------------------------
# Audit Logs
# ----------------------------------------------------------------------
sql("-- ---------------- Audit Logs ----------------")
audit_id = 28400
actions = [
    ("APPROVE_QUESTION", "Question"), ("REJECT_QUESTION", "Question"),
    ("CREATE_QUIZ", "Quiz"), ("UPDATE_QUIZ", "Quiz"), ("DELETE_QUESTION", "Question"),
    ("ASSIGN_QUIZ", "QuizAssignment"), ("CREATE_USER", "User"), ("DISABLE_USER", "User"),
]
for _ in range(80):
    actor = random.choice(instructor_ids + reviewer_ids + [users[0][0]])
    action, entity = random.choice(actions)
    entity_id = random.randint(1, 500)
    days_ago = random.randint(0, 60)
    sql(f"INSERT INTO audit_logs (id, user_id, action, entity_name, entity_id, details, timestamp) VALUES "
        f"({audit_id}, {actor}, '{action}', '{entity}', {entity_id}, "
        f"'{action} performed on {entity} #{entity_id}', DATE_SUB(NOW(), INTERVAL {days_ago} DAY));")
    audit_id += 1
sql("")

# ----------------------------------------------------------------------
# Settings singletons (id is always 1 by entity design)
# ----------------------------------------------------------------------
sql("-- ---------------- Settings (singleton rows, id=1 by design) ----------------")
sql("INSERT INTO application_settings (id, site_name, site_logo_url, timezone, date_format, items_per_page, maintenance_mode) "
    "VALUES (1, 'Quiz Admin Portal', '', 'UTC', 'dd-MM-yyyy', 20, 0) "
    "ON DUPLICATE KEY UPDATE site_name=VALUES(site_name);")
sql("INSERT INTO security_settings (id, password_min_length, session_timeout_minutes, max_login_attempts, enable_two_factor) "
    "VALUES (1, 8, 30, 5, 0) ON DUPLICATE KEY UPDATE password_min_length=VALUES(password_min_length);")
sql("INSERT INTO otp_settings (id, otp_length, otp_expiry_minutes, otp_provider, enabled) "
    "VALUES (1, 6, 5, 'TWILIO', 1) ON DUPLICATE KEY UPDATE otp_length=VALUES(otp_length);")
sql("INSERT INTO payment_gateway_settings (id, provider, api_key, api_secret, currency, test_mode) "
    "VALUES (1, 'RAZORPAY', 'test_key_placeholder', 'test_secret_placeholder', 'USD', 1) "
    "ON DUPLICATE KEY UPDATE provider=VALUES(provider);")
sql("INSERT INTO email_configuration (id, smtp_host, smtp_port, smtp_username, smtp_password, from_address, use_tls) "
    "VALUES (1, 'smtp.example.com', 587, 'no-reply@quizapp.com', 'placeholder', 'no-reply@quizapp.com', 1) "
    "ON DUPLICATE KEY UPDATE smtp_host=VALUES(smtp_host);")
sql("")

sql("SET FOREIGN_KEY_CHECKS=1;")
sql("")
sql("-- ============================================================")
sql("-- Row count summary (approx):")
sql(f"--   roles: {len(roles)}   users: {len(users)}   user_groups: {len(groups)}")
sql(f"--   subjects: {len(subjects)}   categories: {len(categories)}   tags: {len(tags)}")
total_options = sum(2 if q[4] == TRUE_FALSE_TYPE_ID else 4 for q in questions)
sql(f"--   questions: {len(questions)}   question_options: {total_options}   question_tags: ~{len(questions)*2}")
sql(f"--   quizzes: {len(quizzes)}   quiz_schedules: {len(quizzes)}   quiz_results: 315")
sql(f"--   practice_sets: {len(practice_sets)}   practice_attempts: 200   audit_logs: 80")
sql("-- ============================================================")

with open("seed-master-data-dump.sql", "w") as f:
    f.write("\n".join(OUT))

print(f"Generated {len(OUT)} SQL lines -> seed-master-data-dump.sql")
